### ISSUE TITLE
AM/PM cutoff off-by-one?

### ISSUE THREAD

**Issue by woodwardjd** [mgold/elm-date-format#14]
https://github.com/mgold/elm-date-format/blob/master/src/Date/Format.elm#L89-L100

I feel like this should be `< 12` instead of `< 13`.  At least in the US.  Unless I'm missing something blindingly obvious.  Which is very possible.

Consider 12:52, which is afternoon, which should get `PM`, but currently gets `AM`.

I'll submit a PR if it turns out I'm right.

**Comment by mgold** [comment]
I think you're right. Hours 0-11 correspond to 12am-11am, so the cutoff should be `<12` as you suggest. I'll take care of it.

**Comment by mgold** [comment]
Fixed and released in 1.1.5. Thanks!

**Comment by woodwardjd** [comment]
No, thank *you*!  This was much faster than me figuring out how to get `elm-package` to use a branch on a github repo, if that's even possible.

**Comment by mgold** [comment]
It's not - you have to clone the repo through GitHub.
