### ISSUE TITLE
`format "%H" 0` shows "09"

### ISSUE THREAD

**Issue by aiya000** [mgold/elm-date-format#28]
Hi, thank you for present great library! :smiley:

In my opinion,
`format "%H" 0` should show "00",
but it shows "09".

%k, %I, and %l are same, it shows with "9".

Is this correct behabior?

Sorry if my opinion is wrong :persevere:

**Comment by mgold** [comment]
This is likely a timezone issue: midnight UTC is 9 o'clock locally, or perhaps the reverse.

**Comment by aiya000** [comment]
I understood, thanks :smile:

should it be fixed in elm-date-format?

**Comment by mgold** [comment]
There is work in progress to better support timezones. It will probably happen over at [ryannhg/date-format](https://github.com/ryannhg/date-format/tree/master)

**Comment by aiya000** [comment]
Thanks!
