### ISSUE TITLE
Add new release with "elm-version" in elm-package.json.

### ISSUE THREAD

**Issue by manleyjster** [mgold/elm-date-format#3]
Hi - 

It's not possible to use this package right now with 0.15 of the Elm platform because the latest version of the project with `elm-version` defined in `elm-package.json` hasn't yet been tagged as a release.

Could you tag `master` with a new release so that the updated `elm-package.json` will get pulled down by `elm package install`?

**Comment by mgold** [comment]
Oh no! Should be fixed now.

**Comment by amitaibu** [comment]
I'm also unable to install using `elm-package install mgold/elm-date-format`:

```
Error: Unable to get elm-package.json for mgold/Elm-Format-String 1.0.0
Missing field "elm-version", acceptable versions of the Elm Platform (e.g. "0.15.1 <= v < 0.16.0").
    Check out an example elm-package.json file here:
    <https://raw.githubusercontent.com/evancz/elm-html/master/elm-package.json>
```

**Comment by mgold** [comment]
You need to use 1.0.1. If there are further concerns, please open a new issue.

**Comment by amitaibu** [comment]
Yeah, for some reason it was looking only for `1.0.0` - anyway, I'll check on another computer. Sorry for the noise ;)

**Comment by mgold** [comment]
You likely need to update the dependency is `elm-package.json`.
