### ISSUE TITLE
`%I` renders `12` as `00`

### ISSUE THREAD

**Issue by Fresheyeball** [mgold/elm-date-format#9]
midnight is `"00"` with `%I`, expected is `"12"`

**Comment by Fresheyeball** [comment]
:+1:  Thank you. Please let me know when this gets published.

**Comment by mgold** [comment]
Well I would have if you had given me just a moment. :stuck_out_tongue_winking_eye: 

It's published.

cc @rluiten who will want to make the same change downstream.

**Comment by Fresheyeball** [comment]
haha, nice.

**Comment by rluiten** [comment]
This problem appears to affect both %I (upperacse i) and %l (lower case l)

**Comment by mgold** [comment]
:anguished: :rage: :anger: :boom: 

Fixed 1.1.2.
